name: Release nest-utils

on:
  workflow_dispatch:
  push:
    tags:
    - "nest-utils-*"

jobs:
  release:
    uses: ../release_template.yml
    with:
      PATH: packages/nest-utils
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
