name: main

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  run_checks:
    name: Run code checks
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_run_checks.yml@v4.0.0
    with:
      PNPM_BUILD: true

  run_unit_tests:
    name: Run tests (vitest)
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_run_tests_vitest.yml@v4.0.0
    with:
      PNPM_BUILD: true
      COVERAGE_FILENAME: reports/vitest/coverage/cobertura-coverage.xml
      COVERAGE_FAIL_BELOW_MIN: 100

  run_release_please_prerelease:
    name: Run release-please prerelease
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_release-please.yml@v4.0.0
    needs:
    - run_checks
    - run_unit_tests
    with:
      ARGS: "--prerelease"
    secrets:
      TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}

  run_release_please:
    name: Run release-please
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_release-please.yml@v4.0.0
    needs:
    - run_checks
    - run_unit_tests
    secrets:
      TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}

# Run pnpx release-please \
#   pnpx release-please \
#   --repo-url=spuxx1701/jslibs \
#   --token=*** \
#   --config-file=.release-please/config.json \
#   --manifest-file=.release-please/manifest.json --prerelease \
#   release-pr
