name: Main

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run_checks:
    name: Run code checks
    uses: spuxx-dev/ci-cd/.github/workflows/pnpm_run_checks.yml@v4.0.0
    with:
      PNPM_BUILD: true

  run_unit_tests:
    name: Run tests (vitest)
    uses: spuxx-dev/ci-cd/.github/workflows/pnpm_run_tests_vitest.yml@v4.0.0
    with:
      PNPM_BUILD: true

  run_release_please:
    name: Run release-please
    uses: spuxx-dev/ci-cd/.github/workflows/pnpm_release-please.yml@v4.0.0
    needs:
    - run_checks
    - run_unit_tests
    secrets:
      TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}

  deploy_pages:
    name: Deploy Storybook to GitHub Pages
    runs-on: ubuntu-latest
    needs:
    - run_checks
    - run_unit_tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      with:
        install_command: pnpm -r install
        build_command: pnpm build:storybook
        path: apps/storybook/dist
        checkout: false