name: Main

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run_release_please:
    name: Release Please
    uses: spuxx-dev/ci-cd/.github/workflows/pnpm_release-please.yml@v5.0.0
    secrets:
      TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}

  quality_gates:
    name: Quality Gates
    uses: ./.github/workflows/quality_gates.yml

  deploy_pages:
    name: Deploy GitHub Pages
    uses: ./.github/workflows/pages.yml
    needs:
    - quality_gates