name: main

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  run_checks:
    name: Run code checks
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_run_checks.yml@v4.0.0
    with:
      PNPM_BUILD: true

  run_unit_tests:
    name: Run tests (vitest)
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_run_tests_vitest.yml@v4.0.0
    with:
      PNPM_BUILD: true
      COVERAGE_FILENAME: reports/vitest/coverage/cobertura-coverage.xml
      COVERAGE_FAIL_BELOW_MIN: 100

  create_prerelease_pr:
    name: Run release-please (prerelease)
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_release-please.yml@v4.0.0
    needs:
    - run_checks
    - run_unit_tests
    with:
      ARGS: "--versioning-strategy=prerelease"
    secrets:
      TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}

  run_release_please:
    name: Run release-please
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_release-please.yml@v4.0.0
    needs:
    - create_prerelease_pr
    secrets:
      TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
