name: Releases (@spuxx/nest-auth)

on:
  workflow_dispatch:
  push:
    tags:
    - "nest-auth-*"

permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Release artifact (@spuxx/nest-auth)
    uses: ./.github/workflows/release.yml
    with:
      PATH: packages/nest-auth
