name: Releases (@spuxx/solid)

on:
  workflow_dispatch:
  push:
    tags:
    - "solid-*"

permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Release artifact (@spuxx/solid)
    uses: ./.github/workflows/release.yml
    with:
      PATH: packages/solid
