name: "@spuxx/nest-utils"

on:
  workflow_dispatch:
  push:
    tags:
    - "nest-utils-*"

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      PATH: packages/nest-utils
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
