name: Releases (@spuxx/nest-utils)

on:
  workflow_dispatch:
  push:
    tags:
    - "nest-utils-*"

permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Release artifact (@spuxx/nest-utils)
    uses: ./.github/workflows/release.yml
    with:
      PATH: packages/nest-utils
