name: Release Template

on:
  workflow_call:
    inputs:
      PATH:
        required: true
        type: string
        description: "Path to the package to be released"
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  build_and_publish:
    name: Build and publish artifact
    uses: spuxx-dev/ci-cd/.github/workflows/pnpm_build_and_publish.yml@v5.0.0
    with:
      PATH: ${{ inputs.PATH }}
      BUILD_COMMAND: pnpm -r --filter './packages/**' build
