name: release

on:
  workflow_dispatch:
  push: tags:*-v* - "*-v*"
jobs:
  run_checks:
    name: Run code checks
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_run_checks.yml@v4.0.0

  run_unit_tests:
    name: Run unit tests
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_run_unit_tests.yml@v4.0.0
    with:
      COVERAGE_FILENAME: reports/vitest/coverage/cobertura-coverage.xml
      COVERAGE_FAIL_BELOW_MIN: 100

  build_and_publish:
    name: Build and publish artifact(s)
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_build_and_publish_monorepo.yml@v4.0.0
    needs:
    - run_checks
    - run_unit_tests
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
